### PR TITLE
Add eslint configuration; eslint files

### PR DESCRIPTION
**Pull request by JexUK**
⚠️ **WARNING: THIS COMMIT HAS NOT BEEN TESTED IN A DEVELOPMENT ENVIRONMENT.**
**PLEASE VERIFY THERE ARE NO BREAKING CHANGES BEFORE PULLING INTO THE MAIN BRANCH.**

This PR is implementing the use of ESLint into Dashactyl. As a result of this, code produced for Dashactyl will be guaranteed to be more formatted in terms of every file following the same guidelines. 

Every file has been modified to conform to ESLint's rules in terms of code formatting.

If there any changes which cause systems to break or fail, please let me know before accepting this PR and fix it before it is pulled.

### CODE REVIEW

**Comment by manouelispro** [comment]
did you test it?

**Comment by real2two** [comment]
this isnt even the latest version of v1

**Comment by JexUK** [comment]
As the repository has been updated to the latest version I'll update this PR accordingly

**Comment by JexUK** [comment]
This PR does not need updating, and is ready for a pull when reviewed.

**Pull request merged**
